# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('register_time', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.CharField(default='-', max_length=100)),
                ('phone', models.CharField(default='-', max_length=100)),
                ('living_area', models.CharField(default='-', max_length=100)),
                ('password', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Has_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='*.jpg', upload_to='photos/')),
                ('view', models.CharField(default='-', max_length=100)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_time', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(default='-', max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('make', models.CharField(default='-', max_length=100)),
                ('model', models.CharField(default='-', max_length=100)),
                ('status', models.CharField(choices=[('-', '---'), ('Green', 'Available'), ('Red', 'Sold'), ('Yellow', 'Pending')], default='-', max_length=100)),
                ('mileage', models.IntegerField(default=0)),
                ('trim', models.CharField(default='-', max_length=100)),
                ('list_price', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(default=0)),
                ('color_ext', models.CharField(choices=[('-', '---'), ('beige', 'Beige'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('burgundy', 'Burgundy'), ('camouflage', 'Camouflage'), ('charcoal', 'Charcoal'), ('gold', 'Gold'), ('gray', 'Gray'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('turquoise', 'Turquoise'), ('white', 'White'), ('yellow', 'Yellow')], default='-', max_length=100)),
                ('color_int', models.CharField(choices=[('-', '---'), ('beige', 'Beige'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('burgundy', 'Burgundy'), ('camouflage', 'Camouflage'), ('charcoal', 'Charcoal'), ('gold', 'Gold'), ('gray', 'Gray'), ('green', 'Green'), ('lime', 'Lime'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('turquoise', 'Turquoise'), ('white', 'White'), ('yellow', 'Yellow')], default='Bei', max_length=100)),
                ('drive', models.CharField(choices=[('-', '---'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('4WD', 'Four Wheel Drive'), ('AWD', 'All Wheel Drive')], default='-', max_length=100)),
                ('engine', models.CharField(choices=[('-', '---'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('10', '10'), ('12', '12'), ('r', 'Rotary')], default='-', max_length=100)),
                ('transmission', models.CharField(choices=[('-', '---'), ('A', 'Automatic'), ('M', 'Manual')], default='-', max_length=100)),
                ('fuel', models.CharField(choices=[('-', '---'), ('g', 'Gasoline'), ('d', 'Diesel'), ('h', 'Hybrid'), ('e', 'Electronic')], default='-', max_length=100)),
                ('body_type', models.CharField(choices=[('-', '---'), ('Se', 'Sedan'), ('Co', 'Coupe'), ('Co', 'Convertible'), ('SU', 'SUV'), ('Ha', 'Hatchback'), ('Wa', 'Wagon'), ('Mi', 'Minivan'), ('Mo', 'Motorcycle')], default='-', max_length=100)),
                ('top_type', models.CharField(choices=[('-', '---'), ('Co', 'Convertible Softtop'), ('Co', 'Convertible Hardtop'), ('Su', 'Sun Roof'), ('Mo', 'Moon Roof'), ('TT', 'T-Top'), ('Pa', 'Panorama Sunroof')], default='-', max_length=100)),
                ('interior_type', models.CharField(choices=[('-', '---'), ('Cl', 'Cloth'), ('Le', 'Leather'), ('Vi', 'Vinyl')], default='-', max_length=100)),
                ('door', models.IntegerField(default=0)),
                ('carfaxPath', models.CharField(default='-', max_length=100)),
                ('condition', models.CharField(default='-', max_length=100)),
                ('owner_num', models.IntegerField(default=0)),
                ('handler', models.CharField(default='-', max_length=100)),
                ('location', models.CharField(default='-', max_length=100)),
                ('in_stock_time', models.DateTimeField(default=datetime.date(1970, 1, 1))),
                ('deposit_paid_time', models.DateTimeField(default=datetime.date(1970, 1, 1))),
                ('sold_time', models.DateTimeField(default=datetime.date(1970, 1, 1))),
                ('eb_Power_Mirrors', models.BooleanField(default=False)),
                ('eb_Power_Windows', models.BooleanField(default=False)),
                ('eb_Traction_Control', models.BooleanField(default=False)),
                ('eb_Stability_Control', models.BooleanField(default=False)),
                ('eb_Cruise_Control', models.BooleanField(default=False)),
                ('eb_Security_System', models.BooleanField(default=False)),
                ('eb_Tire_Pressure_Monitoring_System', models.BooleanField(default=False)),
                ('eb_Radio_CD_Player', models.BooleanField(default=False)),
                ('eb_AUX', models.BooleanField(default=False)),
                ('eb_USB', models.BooleanField(default=False)),
                ('eb_Steering_Wheel_Audio_Control', models.BooleanField(default=False)),
                ('eb_AntiLock_Brake_System', models.BooleanField(default=False)),
                ('eb_AC', models.BooleanField(default=False)),
                ('es_Universal_Garage_Opener', models.BooleanField(default=False)),
                ('es_Power_Seats_Driver', models.BooleanField(default=False)),
                ('es_Power_Seats_Both', models.BooleanField(default=False)),
                ('es_Rain_Sensing_Wiper', models.BooleanField(default=False)),
                ('es_Back_Up_Camera', models.BooleanField(default=False)),
                ('es_Parking_Sensor', models.BooleanField(default=False)),
                ('es_Sunroof', models.BooleanField(default=False)),
                ('es_All_Weather_Floor_Mats', models.BooleanField(default=False)),
                ('es_Automatic_Headlights', models.BooleanField(default=False)),
                ('es_Daytime_Running_Lights', models.BooleanField(default=False)),
                ('es_Tilt_Steering_Wheel', models.BooleanField(default=False)),
                ('es_Navigation_GPS', models.BooleanField(default=False)),
                ('es_Dual_Climate_Control', models.BooleanField(default=False)),
                ('ep_Heads_Up_Display', models.BooleanField(default=False)),
                ('ep_Heated_Seats_Front', models.BooleanField(default=False)),
                ('ep_Heated_Seats_Rear', models.BooleanField(default=False)),
                ('ep_Cooled_Seats_Front', models.BooleanField(default=False)),
                ('ep_Cooled_Seats_Rear', models.BooleanField(default=False)),
                ('ep_Lane_Departure_System', models.BooleanField(default=False)),
                ('ep_Keyless_Entry', models.BooleanField(default=False)),
                ('ep_Keyless_Start', models.BooleanField(default=False)),
                ('ep_Rear_Spoiler', models.BooleanField(default=False)),
                ('ep_Heated_Steering_Wheel', models.BooleanField(default=False)),
                ('ep_Panorama_Sunroof', models.BooleanField(default=False)),
                ('ep_Night_Vision', models.BooleanField(default=False)),
                ('ep_Premium_Stereo', models.BooleanField(default=False)),
                ('notes', models.CharField(default='-', max_length=100)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='sell',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.Vehicle'),
        ),
        migrations.AddField(
            model_name='has_image',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.Vehicle'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.Vehicle'),
        ),
    ]
